### ISSUE TITLE
How did you discover the library? 12/13/2024

### ISSUE THREAD

**Issue by m31coding** [m31coding/fuzzy-search#9]
Hi all,

I noticed that the fuzzy search library is receiving a lot of attention today—thank you so much for your interest and support! I’m curious to know how you discovered it. Could you share where you came across the library?

Your feedback would be greatly appreciated!

Best regards,
Kevin

**Comment by xueyang996** [comment]
from here?
https://www.ruanyifeng.com/blog/2024/12/weekly-issue-329.html
![image](https://github.com/user-attachments/assets/347dc338-f6f8-4fbf-a03c-6ce87804c40d)


> Hi all,
> 
> I noticed that the fuzzy search library is receiving a lot of attention today—thank you so much for your interest and support! I’m curious to know how you discovered it. Could you share where you came across the library?
> 
> Your feedback would be greatly appreciated!
> 
> Best regards, Kevin

**Comment by m31coding** [comment]
Thank you for sharing the link! I am happy to hear that the library is useful for Asian languages. 

Best regards,
Kevin
